package com.example.droolsdemo
import com.example.droolsdemo.pojo.Order1
global com.example.droolsdemo.pojo.Integral integral;

rule "order_rule_1"
    no-loop
    salience 90
    when
        $order:Order1(amount < 100)
    then
        integral.setScore(10);
        System.out.println("全局的加分"+integral.getScore());
        update($order);
//        $a.setScore(0);
        System.out.println("成功匹配到规则一：100元以下 不加分");
end
